# Generated by Django 5.2.4 on 2025-07-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grocerybatch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
