# Generated by Django 5.2.3 on 2025-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("num_children", models.IntegerField(blank=True)),
                ("num_adults", models.IntegerField(blank=True)),
                ("snap", models.BooleanField(default=False)),
                ("wic", models.BooleanField(default=False)),
                ("tanf", models.BooleanField(default=False)),
                ("ssi", models.BooleanField(default=False)),
                ("medicaid", models.BooleanField(default=False)),
                ("food_allergies", models.TextField(blank=True)),
                ("consent_signed", models.BooleanField(default=False)),
                ("staff_signature", models.CharField(max_length=100)),
                ("lease_doc", models.FileField(upload_to="client_docs/")),
                ("id_doc", models.FileField(upload_to="client_docs/")),
                ("bank_statement", models.FileField(upload_to="client_docs/")),
                ("qualified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
