name: Trigger Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  trigger-vercel-deploy:
    name: Trigger Frontend Deployment on Vercel
    runs-on: ubuntu-latest
    
    steps:
      - name: Send deployment trigger to Vercel
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_7jzyGSgBNmIIkRbjcGCL5zVRqYfl/cCXbT24yZo" 